#!/bin/bash

# list picks inside the picks array
# ignores any element that starts with #
# supports:
#           12345       <-- pick a specific commit
#           -twhatever  <-- picks topic 'whatever' (intentionally no space in there)

picks=(
# bootable/recovery
158328
# external/fuse
158329
# external/stlport
158215
# system/sepolicy
158310
# vendor/cm
158322
158325
# build
158189
158324
# frameworks/av
158285
# hardware/libhardware
158286
)

[ ! -f build/envsetup.sh ] && echo "Nah, you don't appear to be at the top of your source tree!" && exit 1

source build/envsetup.sh

for p in ${picks[@]}; do
  if [[ ${p:0:1} == '#' ]]; then
    continue
  elif [[ ${p:0:2} == '-t' ]]; then
    t=`echo $p | sed -r 's/^.{2}//'`
    repopick -t $t
  else
    echo $p
    repopick $p
  fi
done
